on: push
name: Slack GitHub Action
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Action Messager
        SLACK_CHANNEL: dp-isx-returns-notifications
        SLACK_AVATAR: https://www.google.com/url?sa=i&url=http%3A%2F%2Fnickpizzo.github.io%2FFirst-Responsive-Site%2F&psig=AOvVaw1qz5ER34vGplhbuBLXC0eq&ust=1585061369020000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCMDMmvLrsOgCFQAAAAAdAAAAABAI
    with:
        args: 'ENTER MESSAGE HERE'